steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/test_mathtext_fastapi:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/test_mathtext_fastapi:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'test_mathtext_fastapi', '--image', 'gcr.io/$PROJECT_ID/test_mathtext_fastapi:latest', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']