# Generated by Django 4.2.7 on 2023-12-08 12:09

from django.db import migrations, models
import django.db.models.deletion
import mathtext_fastapi.django_logging.django_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('type', models.TextField()),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(default=mathtext_fastapi.django_logging.django_app.models.get_current_datetime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'math_api_activity',
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'In-progress'), ('EE', 'Early exit'), ('CO', 'Completed')], default='IP', max_length=2)),
                ('created_at', models.DateTimeField(default=mathtext_fastapi.django_logging.django_app.models.get_current_datetime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(default=dict)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.activity')),
                ('previous_activity_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.activitysession')),
            ],
            options={
                'db_table': 'math_api_activity_session',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=mathtext_fastapi.django_logging.django_app.models.get_current_datetime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField()),
            ],
            options={
                'db_table': 'math_api_user',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=mathtext_fastapi.django_logging.django_app.models.get_current_datetime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.user')),
            ],
            options={
                'db_table': 'math_api_user_status',
            },
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.user')),
            ],
            options={
                'db_table': 'math_api_user_properties',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bq_message_id', models.TextField(null=True)),
                ('text', models.TextField()),
                ('direction', models.CharField(choices=[('I', 'Inbound'), ('O', 'Outbound')], default='O', max_length=1)),
                ('created_at', models.DateTimeField(default=mathtext_fastapi.django_logging.django_app.models.get_current_datetime)),
                ('activity_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.activitysession')),
                ('previous_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.message')),
            ],
            options={
                'db_table': 'math_api_message',
            },
        ),
        migrations.CreateModel(
            name='MathAnswerMessageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_level', models.IntegerField()),
                ('question_skill', models.TextField()),
                ('question_topic', models.TextField()),
                ('question_number', models.TextField()),
                ('expected_answer', models.TextField()),
                ('answer_type', models.TextField()),
                ('question_micro_lesson', models.TextField()),
                ('nlu_response_data', models.TextField()),
                ('nlu_response_type', models.TextField()),
                ('nlu_response_confidence', models.TextField()),
                ('hint_shown', models.TextField(null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.message')),
            ],
            options={
                'db_table': 'math_api_message_metadata',
            },
        ),
        migrations.AddField(
            model_name='activitysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.user'),
        ),
    ]
