# Generated by Django 4.2.7 on 2023-12-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathtext_fastapi_api_django_logging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='current_activity',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='current_activity_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.activitysession'),
            preserve_default=False,
        ),
    ]
