# Generated by Django 4.2.7 on 2023-12-02 03:25

from django.db import migrations, models
import django.db.models.deletion
import mathtext_fastapi.django_logging.django_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mathtext_fastapi_api_django_logging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=mathtext_fastapi.django_logging.django_app.models.get_current_datetime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.activity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.user')),
            ],
            options={
                'db_table': 'math_api_user_status',
            },
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.user')),
            ],
            options={
                'db_table': 'math_api_user_properties',
            },
        ),
    ]
