# Generated by Django 4.2.7 on 2023-12-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathtext_fastapi_api_django_logging', '0002_userstatus_userproperties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='activitysession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mathanswermessagemetadata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userproperties',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'managed': False},
        ),
    ]
