# Generated by Django 4.2.7 on 2023-12-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathtext_fastapi_api_django_logging', '0002_remove_userstatus_current_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='current_activity_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mathtext_fastapi_api_django_logging.activitysession'),
        ),
    ]
