# Generated by Django 4.2.7 on 2023-12-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathtext_fastapi_api_django_logging', '0003_alter_userstatus_current_activity_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='content',
            new_name='properties',
        ),
    ]
