# Generated by Django 4.2.7 on 2023-12-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathtext_fastapi_api_django_logging', '0005_remove_mathanswermessagemetadata_answer_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='activitysession',
            table='activity_session',
        ),
        migrations.AlterModelTable(
            name='mathanswermessagemetadata',
            table='math_answer_message_metadata',
        ),
        migrations.AlterModelTable(
            name='message',
            table='rori_message',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userproperties',
            table='user_properties',
        ),
        migrations.AlterModelTable(
            name='userstatus',
            table='user_status',
        ),
    ]
