# Generated by Django 4.2.7 on 2023-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathtext_fastapi_api_django_logging', '0006_alter_activity_table_alter_activitysession_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathanswermessagemetadata',
            name='user_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
